global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 127.0.0.1:9093

scrape_configs:

  # Blackbox Exporter自身のメトリクス
  - job_name: "blackbox-exporter"
    static_configs:
      - targets:
          - "127.0.0.1:9115"

  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "192.168.17.134:9100"

  # Blackbox Exporter経由のHTTP監視
  # - job_name: "blackbox-http"
  - job_name: "blackbox-ssh"
    metrics_path: /probe

    params:
      module:
        # - http_2xx
        - ssh_banner

    # ホストの属性をラベルとして付与するために、targetsを外部ファイルに分離（5分ごとにリロード）
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/ssh_server.yml'  # ホスト一覧ファイルを指定
        refresh_interval: 5m

    relabel_configs:
      # 監視対象URLをprobeのtargetパラメータへ渡す
      - source_labels: [__address__]
        target_label: __param_target

      # instanceラベルには監視対象URLを設定
      - source_labels: [__param_target]
        target_label: instance

      # 実際にscrapeする先をBlackbox Exporterに変更
      - target_label: __address__
        replacement: 127.0.0.1:9115
